In [215]:
import numpy as np

In [216]:
np1 = np.array([1, 2, 3, 4, 5])
np1

array([1, 2, 3, 4, 5])

In [217]:
type(np1)

numpy.ndarray

In [218]:
np2 = np.array([1, 2, 'a', 'b'])
np2

array(['1', '2', 'a', 'b'], dtype='<U21')

In [219]:
type(np2)

numpy.ndarray

In [220]:
np3 = np.linspace(1, 20, 20)
np3

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [221]:
np4 = np.arange(0, 10, 1)
np4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [222]:
np5 = np.zeros(10, int)
np5

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [223]:
np6 = np.zeros((2, 2), str)
np6

array([['', ''],
       ['', '']], dtype='<U1')

In [224]:
np7 = np.ones(10, int)
np7

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [225]:
np8 = np.ones((2, 2))
np8

array([[1., 1.],
       [1., 1.]])

In [226]:
np9 = np.eye((3), 4, 0, int)
np9

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [227]:
np10 = np.array([1, 2, 3 ,4, 5, 6])
np10
np10.shape

(6,)

In [228]:
np11 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np11.shape

(3, 3)

In [229]:
np12 = np11.reshape(3, 3)
np12

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [230]:
np13 = np.arange(11, 20).reshape(3, 3)
np13

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [231]:
np14 = np.add(np12, np13)
np14

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [232]:
np15 = np.subtract(np12, np13)
np15

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [233]:
np16 = np.multiply(np12, np13)
np16

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [234]:
np17 = np.divide(np13, np12)
np17

array([[11.        ,  6.        ,  4.33333333],
       [ 3.5       ,  3.        ,  2.66666667],
       [ 2.42857143,  2.25      ,  2.11111111]])

In [235]:
np18 = np.remainder(np13, np12)
np18

array([[0, 0, 1],
       [2, 0, 4],
       [3, 2, 1]])

In [236]:
np19 = np18
np19

array([[0, 0, 1],
       [2, 0, 4],
       [3, 2, 1]])

In [237]:
np20 = np19.copy()
np20

array([[0, 0, 1],
       [2, 0, 4],
       [3, 2, 1]])

In [238]:
np19[1, 1] = 100
np19

array([[  0,   0,   1],
       [  2, 100,   4],
       [  3,   2,   1]])

In [239]:
np20

array([[0, 0, 1],
       [2, 0, 4],
       [3, 2, 1]])

In [240]:
np18[1, 1] = 200
np18

array([[  0,   0,   1],
       [  2, 200,   4],
       [  3,   2,   1]])

In [241]:
np19

array([[  0,   0,   1],
       [  2, 200,   4],
       [  3,   2,   1]])

In [242]:
np21 = np.array([[1, 2, 3], [4, 5, 6]])
np21

array([[1, 2, 3],
       [4, 5, 6]])

In [243]:
np22 = np.append(np21, [[7, 8, 9]], 0)
np22

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [244]:
np22 = np.append(np22, [[0], [0], [0]], 1)
np22

array([[1, 2, 3, 0],
       [4, 5, 6, 0],
       [7, 8, 9, 0]])

In [246]:
np23 = np.insert(np22, 3, [[10, 11, 12, 0]], 0)
np23

array([[ 1,  2,  3,  0],
       [ 4,  5,  6,  0],
       [ 7,  8,  9,  0],
       [10, 11, 12,  0]])

In [247]:
np24 = np.matrix(np.arange(1, 21).reshape(4, 5))
np24

matrix([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])

In [249]:
np25 = np.matrix(np.arange(11, 31).reshape(4, 5))
np25

matrix([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]])

In [252]:
np26 = np.dot(np24, np25.T)
np26

matrix([[ 205,  280,  355,  430],
        [ 530,  730,  930, 1130],
        [ 855, 1180, 1505, 1830],
        [1180, 1630, 2080, 2530]])

In [254]:
np.linalg.det(np26)

np.float64(0.0)