In [136]:
import numpy as np

In [137]:
np1 = np.array([1, 2, 3, 4, 5])
np1

array([1, 2, 3, 4, 5])

In [138]:
type(np1)

numpy.ndarray

In [139]:
np2 = np.array([1, 2, 'a', 'b'])
np2

array(['1', '2', 'a', 'b'], dtype='<U21')

In [140]:
type(np2)

numpy.ndarray

In [141]:
np3 = np.linspace(1, 20, 20)
np3

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [142]:
np4 = np.arange(0, 10, 1)
np4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
np5 = np.zeros(10, int)
np5

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [144]:
np6 = np.zeros((2, 2), str)
np6

array([['', ''],
       ['', '']], dtype='<U1')

In [145]:
np7 = np.ones(10, int)
np7

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [146]:
np8 = np.ones((2, 2))
np8

array([[1., 1.],
       [1., 1.]])

In [147]:
np9 = np.eye((3), 4, 0, int)
np9

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [148]:
np10 = np.array([1, 2, 3 ,4, 5, 6])
np10
np10.shape

(6,)

In [149]:
np11 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np11.shape

(3, 3)

In [150]:
np12 = np11.reshape(3, 3)
np12

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [151]:
np13 = np.arange(11, 20).reshape(3, 3)
np13

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [152]:
np14 = np.add(np12, np13)
np14

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [153]:
np15 = np.subtract(np12, np13)
np15

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [154]:
np16 = np.multiply(np12, np13)
np16

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [155]:
np17 = np.divide(np13, np12)
np17

array([[11.        ,  6.        ,  4.33333333],
       [ 3.5       ,  3.        ,  2.66666667],
       [ 2.42857143,  2.25      ,  2.11111111]])

In [156]:
np18 = np.remainder(np13, np12)
np18

array([[0, 0, 1],
       [2, 0, 4],
       [3, 2, 1]])

In [157]:
np19 = np18
np19

array([[0, 0, 1],
       [2, 0, 4],
       [3, 2, 1]])

In [158]:
np20 = np19.copy()
np20

array([[0, 0, 1],
       [2, 0, 4],
       [3, 2, 1]])

In [159]:
np19[1, 1] = 100
np19

array([[  0,   0,   1],
       [  2, 100,   4],
       [  3,   2,   1]])

In [160]:
np20

array([[0, 0, 1],
       [2, 0, 4],
       [3, 2, 1]])

In [161]:
np18[1, 1] = 200
np18

array([[  0,   0,   1],
       [  2, 200,   4],
       [  3,   2,   1]])

In [162]:
np19

array([[  0,   0,   1],
       [  2, 200,   4],
       [  3,   2,   1]])

In [163]:
np21 = np.array([[1, 2, 3], [4, 5, 6]])
np21

array([[1, 2, 3],
       [4, 5, 6]])

In [170]:
np22 = np.append(np21, [[7, 8, 9]], 0)
np22

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [177]:
np22 = np.append(np22, [[0], [0], [0]], 1)
np22

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2